#include <algorithm>
#include <regex>
#include <ctype.h>
#include <iostream>
#include <cstring>
#include <fstream>
#include <sstream>
#include <map>
#include <string>
#include <utility>
#include <vector>
#include <locale>